### PR TITLE
CCIP-014: Upgrade to pox-3

### PR DESCRIPTION
**Pull request by Rapha-btc**
# CCIP-014

## Preamble

| CCIP Number   | 014                                              |
| ------------- | ------------------------------------------------ |
| Title         | Upgrade to pox 3        |
| Author(s)     | Raphael R. Sierra rapha@fontainebleau-management.com            |
|               |    On behalf of the community, see discussion details in issue https://github.com/citycoins/governance/issues/13 and in Discord channels    |
|               |                 |
| Consideration | Economic, Governance, Technical                  |
| Type          | Standard                                         |
| Status        | Draft                                        |
| Created       | 2023-04-19                                       |
| License       | BSD-2-Clause                                     |
| Replaces      | CCD002, CCD006, CCD001, CCIP-011 |

## Summary

1. Set minting contract for mia and nyc to a version using pox 3
2. Add treasury that uses the minting contract from 1
3. Transfer stx to treasury of 3
4. Set pool address 
5. Delegate stx to pool
6. Pay stackers that were not paid in cycle 55 due to bug

Please kindly suggest edits to this first draft.

### CODE REVIEW

**Comment by whoabuddy** [comment]
Hey @Rapha-btc - thanks for getting this started! Based on the discussions in Discord I think we should separate our intentions into three SIPs:

CCIP-014: Implementing pox-3 and stacking the city treasuries
CCIP-015: Implementing a community voting method in proposals
CCIP-016: Paying out missed rewards in cycles 54 or 55

With this the first would be scoped to the changes we need now in line with pox-3.

The second would represent the voting method where we can document it's usage across different proposals, as well as replace it with a future method using the same CCIP process.

The third would be the place to store calculations and related proofs for claims, where we can try to use on-chain data where possible (`at-block` will come in handy!).

Given that structure let's start filling in this draft with the information we have for the pox-3 upgrade. An easy way to start is to copy all the [headings from CCIP-000](https://github.com/citycoins/governance/blob/main/ccips/ccip-000/ccip-000-citycoins-improvement-proposal-process.md), and we can fill them in [as the implementation progresses](https://github.com/citycoins/protocol/pull/59).

**Comment by whoabuddy** [comment]
Actually, looking closer at the PR, instead of attaching the markdown in the text file to your comment you should include the code as part of your changes.

You can do that by renaming the file `ccips/ccip-014/first-draft` to `ccips/ccip-014/ccip-014-upgrade-to-pox-3.md` then putting the contents inside. 

Then it will show the code line-by-line and display it correctly on GitHub for the PR.

There are also a few spots where pox-2 should be updated to pox-3 as well. 

Let me know if you have any questions!

**Comment by Rapha-btc** [comment]
- [ ]  Renamed

- [ ]  Copy-pasted template in Files

- [ ] Corrected typos 2-> 3

Thanks for your kind guidelines. Looking forward to review code edits and continue to learn!

**Comment by whoabuddy** [comment]
FYI - going to add some commits to keep this moving along, and contracts are [still being tracked in this PR](https://github.com/citycoins/protocol/pull/59).

**Comment by Rapha-btc** [comment]
An expedited vote is indeed the preferred approach for making changes and fixes that do not alter the governance of citycoins but rather ensure their compatibility with Stacks updates.

Regarding the new contracts, there are four new contracts: "ccd006-citycoin-mining-v2" and "ccd002-treasury-v2" for two different cities, correct?

Does the restriction on executing proposals also result in the creation of a version 2 (v2) for ccd001?

**Comment by whoabuddy** [comment]
> Regarding the new contracts, there are four new contracts: "ccd006-citycoin-mining-v2" and "ccd002-treasury-v2" for two different cities, correct?

The four contracts deployed were:
- [ccip-014-pox-3](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccip014-pox-3?chain=mainnet)
- [ccd002-treasury-mining-mia-v2](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd002-treasury-mia-mining-v2?chain=mainnet)
- [ccd002-treasury-mining-nyc-v2](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd002-treasury-nyc-mining-v2?chain=mainnet)
- [ccd006-citycoin-mining-v2](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd006-citycoin-mining-v2?chain=mainnet)

In addition to that, a [trait representing CCIP-015](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccip015-trait?chain=mainnet) was deployed and used, and is available for future proposals that include a vote.

The contract for `ccip-014-pox-3` failed to execute though due to one of the cycles it was attempting to close out being active, see note from Discord:

> Bad news: the [final tx failed](https://explorer.hiro.so/txid/0xb4149b1885697d4f0314329c4d40eac29c73c2c0cc70dede9a8f2c4af49a7f39?chain=mainnet).
> CCIP-014 was trying to pay out cycles 56-59  but cycle 59 isn't complete, so we get the error u7006 or ERR_INCOMPLETE_CYCLE.

Following that, `ccip-014-pox-3-v2` was deployed and executed after checking the `is-executable` function of the original `ccip-014-pox-3`.

```clarity
(define-read-only (is-executable)
  (contract-call? .ccip014-pox-3 is-executable)
)
```

> The restriction on executing proposals is handled at the ccip014 level at this time, correct?

Yes, per the [CCIP-015 draft spec](https://github.com/citycoins/governance/pull/15) and using the trait listed above (first implementation). Any proposal can do the same, and a new method could be defined by a new CCIP should we need it.

> Could you please share the treasury-v2 links as well?

Linked the deployed contracts in my comments above. :slightly_smiling_face:

**Comment by whoabuddy** [comment]
This is ready to merge! Congrats everyone for making it happen, and @Rapha-btc for kicking off the efforts!

**Pull request merged**
